name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: locate sdkmanager
      run: which sdkmanager

    - name: Locate Gradle
      run: which gradle

    - name: Setup Gradle
      run: gradle wrapper

    - name: Build project
      run: bash ./gradlew build

    - name: Install tree
      run: sudo apt install -y tree

    - name: Show directory structure
      run: tree .

    - uses: actions/upload-artifact@v2
      with:
        path: .
