name: CI
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    # - uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8

    # - name: install linux tools
    - run: sudo apt install -y tree wget unzip python3

    # - name: download android ndk 20
    - run: wget https://dl.google.com/android/repository/android-ndk-r20b-linux-x86_64.zip

    # - name: unzip ndk
    - run: unzip android-ndk-r20b-linux-x86_64.zip

    # - name: setup android sdk
    - run: wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    - run: unzip commandlinetools-linux-9477386_latest.zip
    - run: mkdir -p ANDROID_SDK_ROOT
    - run: ./cmdline-tools/bin/sdkmanager --sdk_root=ANDROID_SDK_ROOT --no_https --update
    - run: ./cmdline-tools/bin/sdkmanager --sdk_root=ANDROID_SDK_ROOT --no_https --licenses
      # run: ./cmdline-tools/bin/sdkmanager --sdk_root=ANDROID_SDK_ROOT --install "platform-tools" "platforms;android-29" "build-tools;29.0.3"
    # - run: ./cmdline-tools/bin/sdkmanager --sdk_root=ANDROID_SDK_ROOT --licenses "build-tools;28.0.3" "ndk;20.1.5948944"
    - run: ./cmdline-tools/bin/sdkmanager --sdk_root=ANDROID_SDK_ROOT --no_https --install "ndk;20.1.5948944"
    - run: ./cmdline-tools/bin/sdkmanager --sdk_root=ANDROID_SDK_ROOT --no_https --install "build-tools;28.0.3"

    # - name: setup local.properties for gradle
    - run: python3 setup_ndk_linux.py
      # run: source ./custom_bashrc.sh

    # - name: show directory structure
    - run: tree .

      # run: which gradle
    - run: wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
    - run: unzip gradle-6.5-bin.zip
    - run: ./gradle-6.5/bin/gradle wrapper
    - run: bash ./gradlew build

    - uses: actions/upload-artifact@v2
      with:
        path: app/build/outputs/apk/debug/app-debug.apk
