name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:

  - uses: actions/checkout@v2

  - uses: actions/setup-java@v1
    with:
      java-version: 1.8

  - name: Setup Gradle
    run: gradle wrapper

  - name: Build project
    run: bash ./gralew

  - name: Install tree
    run: sudo apt install -y tree

  - name: Show directory structure
    run: tree .
